# Generated by Django 6.0.2 on 2026-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="前日_競走馬拡張",
            name="JRA成績",
            field=models.CharField(max_length=12),
        ),
    ]
