# Generated by Django 3.0.6 on 2020-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='馬基本情報',
            name='血統登録番号',
            field=models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False),
        ),
    ]
